### ISSUE TITLE
No text centered

### ISSUE THREAD

**Issue by cjmaxik** [aziz/DistractionFreeWindow#1]
No text centered

**Comment by sundarv85** [comment]
+1 from me. It would be good if the text can be centred, as that is the most beautiful part of distraction free editing.

**Comment by JulianSchuette** [comment]
+1

**Comment by diegobit** [comment]
I added this and made a pull request! :)

**Comment by jrappen** [comment]
To review the related changes see:

* aziz/DistractionFreeWindow@ad60fd4
