### ISSUE TITLE
Automatic mode setting

### ISSUE THREAD

**Issue by jrappen** [aziz/DistractionFreeWindow#10]
After pondering the idea of implementing the enhancement of adding an automatic mode to the DFW plug-in, I have decided against it. Switching from toggling via keyboard shortcuts to automatic toggling will probably confuse and/or anger some users. The other issue is maintainability.

**Comment by jrappen** [comment]
* 1) Nothing to say yet, haven't tested it.
* 2) Have been using the autosidebar python file for a while now to see what it is like, not sure it's a good idea. It is too distracting because you really gotta watch your mouse's position and it really takes a lot of time for the UI to change from one state to the other....and ST should probably be used by keyboard only for speed. I got rid of it again.

**Comment by jrappen** [comment]
1. AutoHideSideBar is much better in regards to user experience. Interested in adding this functionality? I could open a develop branch and add a PR.

**Comment by jrappen** [comment]
@aziz I got a working example for ST3116+, so that would drop support for ST2. Should probably be released separately? Should I drop a binary here for you to set up or put it up myself?

**Comment by jrappen** [comment]
As the workarounds tend to get nastier for ST2, I released this as a standalone:

https://github.com/jrappen/sublime-autodistractionfree

:warning: ST3118+

**Comment by nikitavoloboev** [comment]
Is it possible to set automatic mode setting?

**Comment by jrappen** [comment]
@nikitavoloboev try <https://packagecontrol.io/packages/distractionless>?
