### ISSUE TITLE
Not working on ST2 build 2221

### ISSUE THREAD

**Issue by fcccbf8f8f1** [aziz/DistractionFreeWindow#14]
I'm having difficulty getting DistractionFreeWindow to run on ST2 build 2221 running on OS X 10.6.8. Trying to run from either the command palette or key bindings isn't working.

It was working for me previously, but I did a fresh install because of some other issues I was running into, and since reinstalling (via Package Control), I have been getting this error in the console log:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./distraction_free_window.py", line 24, in run
AttributeError: 'Window' object has no attribute 'settings'
```
Any help would be greatly appreciated!

**Comment by jrappen** [comment]
Sorry about that. Give me a few mins and I'll revert the latest changes.

**Comment by jrappen** [comment]
Just pushed `0.5.2`, please give Package Control an hour to update.
