### ISSUE TITLE
DistractionFreeWindow doesn't return to initial state

### ISSUE THREAD

**Issue by oscarmcm** [aziz/DistractionFreeWindow#19]
## A summary of the issue

This Issue is a continuation from #17 and #6 

* Some steps to reproduce.
  1. Just enable DistractionFreeWindow.
  2. Try to restore the UI 

```python
Traceback (most recent call last):
  File "sublime_plugin.py", line 553, in run_
    return self.run()
  File "distraction_free_window in DistractionFreeWindow.sublime-package", line 58, in run
AttributeError: 'Window' object has no attribute 'set_menu_visible'
```

### Environment

```text
DistractionFreeWindow:
    release:        0.6.2

Sublime Text:
    channel:        stable
    version:        Build 3114
    platform:      OSX
    architecture:  x64
```

**Comment by oscarmcm** [comment]
Just ping to @jrappen 😄

**Comment by jrappen** [comment]
@oscarmcm thank you for the report. It seems, Sublime Text cannot hide or show the menu on OSX ... which would make sense as far as I'm guessing. As said in #6 I cannot test it on OSX. I'll move the menu related code to a conditional check for Windows and Linux only.
