### ISSUE TITLE
Toggling DistractionFreeWindow doesn't work

### ISSUE THREAD

**Issue by prashantdawar** [aziz/DistractionFreeWindow#21]
### Description

I clicked keys <kbd>Super</kbd><kbd>F11</kbd> to enable DisctractionFreeWindow and now its not coming back to normal. 

How to bring back to normal mode. <kbd>Super</kbd><kbd>F11</kbd> pressing not working  now. Uninstalling this plugin also not working.

Tried to change keys to <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Shift</kbd><kbd>F11</kbd>, still DistractionFreeWindow not toggling.

How to bring to default look and feel..
### Environment

``` text
DistractionFreeWindow:
    release:        ?

Sublime Text:
    channel:        stable
    version:        Build 3114
    platform:       ?
    architecture:   ?
```

**Comment by jrappen** [comment]
* which OS?
* which version of DistractionFreeWindow?
* before you try again, please open `View > Show Console` from the main menu and paste `import sublime; sublime.log_commands(True)` and hit <kbd>RETURN</kbd>. Please paste a log here. You can then disable logging commands again via `import sublime; sublime.log_commands(False)`.

**Comment by jrappen** [comment]
ping @prashantdawar

**Comment by jrappen** [comment]
@prashantdawar Can't help you unless you provide some more information.
