### ISSUE TITLE
set when it enters distraction free mode

### ISSUE THREAD

**Issue by geniusupgrader** [aziz/DistractionFreeWindow#24]
I'm missing to control the time/keystrokes, when it enters the distraction free mode.
There should be some more settings in general.

### Environment

```text
DistractionFreeWindow:
    release:        0.6.6

Sublime Text:
    channel:        stable
    version:        Build 3126
    platform:       Windows
    architecture:   x64
```

**Comment by jrappen** [comment]
I'm not sure what you want.

**Comment by geniusupgrader** [comment]
Well, it goes automatically in the distraction free mode, after some time. It would be nice to control this time.

**Comment by jrappen** [comment]
Out of the box this package **does not automatically** make Sublime Text enter "Distraction Free" mode, but only toggles upon <kbd>Super</kbd><kbd>F11</kbd>.

Compare:

https://github.com/aziz/DistractionFreeWindow/blob/a5dc5674f1183fb44009d1993cd6b7b55cea6fe3/input-maps/Default.sublime-keymap#L2

https://github.com/aziz/DistractionFreeWindow/blob/a5dc5674f1183fb44009d1993cd6b7b55cea6fe3/distraction_free_window.py#L14

Maybe you added that functionality yourself?

**Comment by geniusupgrader** [comment]
Ah, my bad. I opened this issue in the false repo, I mean this Sublime plugin: [distractionless](https://github.com/jrappen/sublime-distractionless)
