### ISSUE TITLE
Enabling the setting "dfw_hide_gutter": true, keep the gutter hidden after exiting the free distraction window mode

### ISSUE THREAD

**Issue by evandrocoan** [aziz/DistractionFreeWindow#25]
## Short and descriptive example bug report title

Enabling the setting "dfw_hide_gutter": true, keep the gutter hidden after exiting the free distraction window mode.

![back2](https://user-images.githubusercontent.com/5332158/32130876-47059d24-bb7f-11e7-8803-a553c030eb3f.gif)

### Steps to reproduce

1. Enable the Sublime Text gutter.
1. Enable the setting `	"dfw_hide_gutter": true,`
1. Enter on free distraction mode `super+f11`
1. Exit free distraction mode with `super+f11`
1. You gutter still gone.

### Environment

```text
DistractionFreeWindow:
    release:        0.6.7

Sublime Text:
    channel:        dev
    version:        Build 3152 (portable)
    platform:       Windows
    architecture:   x64
    dpi_scale:      1.0
```

**Comment by jrappen** [comment]
@evandrocoan Please re-open this issue, should problems persist.
