### ISSUE TITLE
Centre text just like in Distraction Free Mode

### ISSUE THREAD

**Issue by nikitavoloboev** [aziz/DistractionFreeWindow#27]
It would be really awesome if it would also centre text just like in Distraction Free Mode. 

Like here:
![2018-04-25 at 12 54](https://user-images.githubusercontent.com/6391776/39241626-dc685a7e-4887-11e8-8f48-0f6e023fce2f.png)

**Comment by aziz** [comment]
it can do that. you just need to set it in your user settings file. Read the docs.
https://github.com/aziz/DistractionFreeWindow/blob/70b33db354c8a27f53fed177c359402deee5ecd3/.sublime/settings/distraction_free_window.sublime-settings#L35
