### ISSUE TITLE
Minimap display status not customizable

### ISSUE THREAD

**Issue by Mi-Sky** [aziz/DistractionFreeWindow#28]
## Minimap display status not customizable

**DistractionFreeWindow** forces its own minimap display settings.

### Expected behavior

remember the user's preferred display status for file minimap on the right hand side of the pane. I, for example, prefer no minimap in normal view (when desktop real estate is scarce), and a displayed minimap in the distraction free view (when enough free space on the side is available).

### Actual behavior

DFW forces to always HIDE minimap in distraction free view and to SHOW minimap in normal view. Apart from that, DFW is a GREAT little tool, thanks!

```text
DistractionFreeWindow:
    release:        st3-1.0.0

Sublime Text: 3.1.1
    version:        Build 3176
    platform:       Windows
    architecture:   x64
```

**Comment by eeemda** [comment]
Seconded.

Same OS, version of DFW and Sublime.

**Comment by jrappen** [comment]
Change your settings:

* Sublime Text > Preferences > Settings
* Sublime Text > Preferences > Settings - Distraction Free

Since `v1.0.0` inherits preferences from Sublime Text.

---

/cc @Mi-Sky @eeemda
