### ISSUE TITLE
Rulers lost after exiting distraction free mode

### ISSUE THREAD

**Issue by MoritzBrueckner** [aziz/DistractionFreeWindow#29]
### Summary

If you enter the distraction free mode and exit it, the rulers in your file don't show up until you reopen the file.

### Environment

```text
DistractionFreeWindow:
    release:        1.0.1

Sublime Text:
    channel:        stable
    version:        Build 3.1.1 (3176)
    platform:       Windows
    architecture:   x64
```

**Comment by jrappen** [comment]
Thanks for the report. I'm busy this week, please send a pull request if you need a quick fix.
