### ISSUE TITLE
Word Wrap lost after exiting distraction free mode

### ISSUE THREAD

**Issue by atoav** [aziz/DistractionFreeWindow#30]
### Summary
When I open sublime text with a file open that should wrap it wraps. When I pres <kbd>Shift</kbd> + <kbd>F11</kbd> to go to the "traditional" Distraction Free Mode and exit it again, the Word Wrapping works consistently. If I do the same with DistractionFreeWindow, the file will be wrapped when I enter DistractionFreeWindow, and lose the Wrapping when I exit it.  

The only way to regain my original wrapping is closing the file, and reopening it. I tested this with multiple Filetypes which have a syntax specific settings (including markdown). Maybe it is related to these syntax specific settings?

This might also be related to #29  

### Expected behavior
Exiting DistractionFreeWindow should not change anything at all

### Actual behavior
Exiting DistractionFreeWindow makes `Word Wrap Column: 0` (auto) break.

### Steps to reproduce

1. Open file with SyntaxSpecific wrapping
2. Enter DistractionFreeWindow Mode with <kbd>Win</kbd> + <kbd>F11</kbd>
3. Exit DistractionFreeWindow Mode with <kbd>Win</kbd> + <kbd>F11</kbd>
4. Word Wrap is gone
5. Close and Reopen Sublime (Word Wrap still gone)
6. Close and Reopen the File (Word Wrap is back, till you do Step 2 again)

### Environment
My word wrap settings are at their default values for the distraction free mode, for the user settings and for the syntax specific settings.  

```text
DistractionFreeWindow:
    release:        1.1.0

Sublime Text:
    channel:        stable
    version:        3.1.1 Build 3176
    platform:       Windows
    architecture:   x64
    dpi_scale:      0
```

**Comment by jrappen** [comment]
Thanks for the report. I'm busy this week, please send a pull request if you need a quick fix.
